[package]
name = "pegasus-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
serialport = "4.1"
prost = "0.10"
protobuf = "2.27"
protobuf-codegen-pure = "2.27"

[dependencies.uuid]
version = "1.0.0"
features = [
    "v4",
    "fast-rng",
]