[package]
name = "pegasus-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
serialport = "4.1"
prost = "0.10"
log = "0.4"
env_logger = "0.9"
lightspeed = { git = "https://github.com/devducks/lightspeed", rev = "v0.5.0" }
protobuf = "3.0"
tonic = "0.7"
tokio = { version = "1", features = ["rt-multi-thread"] }
tokio-serial = "5.4"

[dependencies.uuid]
version = "1.0.0"
features = [
    "v4",
    "fast-rng",
]

[[bin]]
name = "pgrpc-server"
path = "src/server.rs"